routes:
  /rss/:
    template: rss
    content_type: text/xml

collections:
  /:
    permalink: /{slug}/
    template: index
    filter: tag:-blog
  /blog/:
    permalink: /blog/{slug}/
    template: blog
    filter: tag:blog
    data: tag.blog
  /translators/:
    permalink: /translators/{slug}/
    template: index
    filter: tag:translators
    data: tag.translators
  /translations/:
    permalink: /translations/{slug}/
    template: index
    filter: tag:translations
    data: tag.translations
  /theories/:
    permalink: /theories/{slug}/
    template: index
    filter: tag:theories
    data: tag.theories

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
